import React from "react";

function Cards() {
  return (
    <div className="flex justify-around leading-6">
      <div className="flex justify-center items-center font-sans flex-col container ">
        <div>
          <h2 className="text-white mt-[80px] mb-[20px] text-[24px] font-bold text-center">
            Sample Books Generated by BookAI
          </h2>

          <p className="text-white text-center">
            Explore some of the captivating books created using our AI
            technology.
          </p>
        </div>

        <div className="mt-[40px] flex justify-around flex-wrap mb-[40px] gap-16 box-border ">
          <div className="flex justify-around gap-16">
            <div className="bg-opacity-5 bg-white flex justify-center items-center flex-col p-[20px] text-center box-border transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
              <div className="h-[300px] w-[200px] mb-[20px] mt-0 mx-auto">
                <img src="src\assets\paradox.png"></img>
              </div>
              <h3 className="text-[1.17rem] font-bold text-white">
                Science Fiction
              </h3>
              <p className="text-center text-wrap text-[#b3b3b3] mb-[10px]">
                "As Dr. Elara stepped through the shimmering portal, she knew
                there was no turning back. The fate of two universes now rested
                in her hands..."
              </p>
              <a
                href="#"
                className="text-[#8a2be2] mt-[10px] transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none hover:text-white"
              >
                Read more
              </a>
            </div>

            <div className="bg-opacity-5 bg-white flex justify-center items-center flex-col p-[20px] text-center box-border transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
              <div className="h-[300px] w-[200px] mb-[20px] mt-0 mx-auto">
                <img src="src\assets\paradox.png"></img>
              </div>
              <h3 className="text-[1.17rem] font-bold text-white">
                Science Fiction
              </h3>
              <p className="text-center text-wrap text-[#b3b3b3] mb-[10px]">
                "As Dr. Elara stepped through the shimmering portal, she knew
                there was no turning back. The fate of two universes now rested
                in her hands..."
              </p>
              <a
                href="#"
                className="text-[#8a2be2] mt-[10px] transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none hover:text-white"
              >
                Read more
              </a>
            </div>

            <div className="bg-opacity-5 bg-white flex justify-center items-center flex-col p-[20px] text-center box-border transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
              <div className="h-[300px] w-[200px] mb-[20px] mt-0 mx-auto">
                <img src="src\assets\paradox.png"></img>
              </div>
              <h3 className="text-[1.17rem] font-bold text-white">
                Science Fiction
              </h3>
              <p className="text-center text-wrap text-[#b3b3b3] mb-[10px]">
                "As Dr. Elara stepped through the shimmering portal, she knew
                there was no turning back. The fate of two universes now rested
                in her hands..."
              </p>
              <a
                href="#"
                className="text-[#8a2be2] mt-[10px] transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none hover:text-white"
              >
                Read more
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Cards;
