import React from "react";

function Card2() {
  return (
    <section className="text-center items-center justify-center">
      <div className="flex justify-around leading-6 box-border">
        <div className="flex justify-center items-center font-sans flex-col container box-border">
            <div className="mx-[20px]">
            <h2 className="text-white mt-[80px] mb-[20px] text-[24px] font-bold text-center">
              Sample Books Generated by BookAI
            </h2>

            <p className="text-white text-center">
              Explore some of the captivating books created using our AI
              technology.
            </p>
          </div>

          <div className="mt-[40px] flex justify-around flex-wrap mb-[40px] gap-16 box-border text-center">
            <div className="bg-opacity-5 bg-white flex justify-center items-center flex-col p-[20px] text-center box-border transition transform hover:-translate-y-4 motion-reduce:transition-none motion-reduce:hover:transform-none w-[300px] h-[534px] rounded-[10px]">
              <div className="h-[300px] w-[200px] mb-[20px] mt-0 mx-auto rounded-[5px]">
                <img src="https://firebasestorage.googleapis.com/v0/b/testing-40b51.appspot.com/o/paradox.png?alt=media&token=ddfc5699-e31a-447f-9918-3bcad6dced2b"></img>
              </div>
              <h3 className=" mt-3 text-[1.17rem] font-bold text-white">
                Science Fiction
              </h3>
              <p className="text-center  text-[#b3b3b3] mb-[10px]">
                "As Dr. Elara stepped through the shimmering portal, she knew
                there was no turning back. The fate of two universes now rested in
                her hands..."
              </p>
              <a href="#" className="text-[#8a2be2] mt-[10px] hover:text-white">
                Read More
              </a>
            </div>

            <div className="bg-opacity-5 bg-white flex justify-center items-center flex-col p-[20px] text-center box-border transition transform hover:-translate-y-4 motion-reduce:transition-none motion-reduce:hover:transform-none w-[300px] h-[534px] rounded-[10px]">
              <div className="h-[300px] w-[200px] mb-[20px] mt-0 mx-auto rounded-[5px]">
                <img src="https://firebasestorage.googleapis.com/v0/b/testing-40b51.appspot.com/o/mist.png?alt=media&token=16958233-54f4-42c3-8712-f72cea57590a"></img>
              </div>
              <h3 className=" mt-3 text-[1.17rem] font-bold text-white">Mystery</h3>
              <p className="text-center text-wrap text-[#b3b3b3] mb-[10px]">
                "The old lighthouse stood silent, its beacon long extinguished.
                But on foggy nights, some swore they could still see its ghostly
                light..."
              </p>
              <a href="#" className="text-[#8a2be2] mt-[10px] hover:text-white">
                Read More
              </a>
            </div>

            <div className="bg-opacity-5 bg-white flex justify-center items-center flex-col p-[20px] text-center box-border transition transform hover:-translate-y-4 motion-reduce:transition-none motion-reduce:hover:transform-none w-[300px] h-[534px] rounded-[10px]">
              <div className="h-[300px] w-[200px] mb-[20px] mt-0 mx-auto rounded-[5px]">
                <img src="https://firebasestorage.googleapis.com/v0/b/testing-40b51.appspot.com/o/ecos.png?alt=media&token=cf3ea386-aa35-4022-ba8a-17a7676583a3"></img>
              </div>
              <h3 className="mt-3 text-[1.17rem] font-bold text-white">Fantasy</h3>
              <p className="text-center text-wrap text-[#b3b3b3] mb-[10px]">
                "The ancient prophecy spoke of a child born with starlight in
                their eyes. As the comet blazed overhead, the kingdom held its
                breath..."
              </p>
              <a href="#" className="text-[#8a2be2] mt-[10px]  hover:text-white">
                Read More
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default Card2;
